#!/usr/bin/env python


from daemon.daemon import DaemonContext
import time
import lockfile
import sys, logging, time
import logging.handlers
from helloworld.hithere import hail


def main() :

    logger = logging.getLogger('main')
    #handler = logging.handlers.SysLogHandler( facility=logging.handlers.SysLogHandler.LOG_LOCAL7)
    handler = logging.handlers.SysLogHandler( address='/dev/log')
    handler.setLevel(logging.DEBUG)
    formatter = logging.Formatter('%(asctime)s ---> %(message)s')
    handler.setFormatter(formatter)
    logger.addHandler(handler)
    logger.setLevel(logging.DEBUG)

    with DaemonContext(pidfile=lockfile.FileLock('/var/run/teapotd.pid')):
        hail() 



if __name__ == '__main__' :
   sys.exit(main())
